<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.github.kjetilv.uplift</groupId>
    <artifactId>uplift</artifactId>
    <version>0.1.1-SNAPSHOT</version>
  </parent>

  <artifactId>uplift-flambda</artifactId>

  <dependencies>
    <dependency>
      <groupId>com.github.kjetilv.uplift</groupId>
      <artifactId>uplift-synchttp</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.github.kjetilv.uplift</groupId>
      <artifactId>uplift-flogs</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.github.kjetilv.uplift</groupId>
      <artifactId>uplift-json</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.github.kjetilv.uplift</groupId>
      <artifactId>uplift-json-gen</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.github.kjetilv.uplift</groupId>
      <artifactId>uplift-kernel</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.github.kjetilv.uplift</groupId>
      <artifactId>uplift-lambda</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.github.kjetilv.uplift</groupId>
      <artifactId>uplift-util</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.github.kjetilv.uplift</groupId>
      <artifactId>uplift-hash</artifactId>
      <version>${project.version}</version>
    </dependency>

    <!-- Flambda is a test harness, so the JUnit API is part of its own API. -->
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
    </dependency>  </dependencies>

</project>
